# Generated by Django 5.2.12 on 2026-03-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
