# Generated by Django 5.2.12 on 2026-03-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='name',
            new_name='about_description',
        ),
        migrations.AddField(
            model_name='about',
            name='about_heading',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
