# Generated by Django 5.2.9 on 2026-09-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
